# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_char', models.CharField(max_length=244)),
                ('a_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_char', models.CharField(max_length=244)),
                ('b_int', models.IntegerField()),
                ('b_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.A')),
            ],
        ),
    ]
