# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_char', models.CharField(max_length=244)),
                ('c_int', models.IntegerField()),
                ('c_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.B')),
            ],
        ),
    ]
