# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_char', models.CharField(max_length=244)),
                ('d_int', models.IntegerField()),
                ('d_for_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.B')),
                ('d_for_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.C')),
            ],
        ),
    ]
