# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d',
            name='d_for_c',
        ),
        migrations.AlterField(
            model_name='c',
            name='c_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.A'),
        ),
        migrations.AlterField(
            model_name='d',
            name='d_for_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.A'),
        ),
    ]
